# -*- coding: ISO-8859-1 -*-
# generated by wxGlade 0.4.1 on Sun Jun 04 13:39:07 2006
#
# $Id: FunctionViewDifferDlg.py 194 2007-04-05 15:31:53Z cameron $
#


import wx
import FunctionViewDiffListCtrl
import FunctionViewStatsListCtrl
# begin wxGlade: dependencies
# end wxGlade

class FunctionViewDifferDlg(wx.Dialog):
    def __init__(self, *args, **kwds):
        self.function_a = []
        self.function_a_current = 0
        
        self.function_b = []
        self.function_b_current = 0
        
        self.parent = kwds["parent"]
        # begin wxGlade: FunctionViewDifferDlg.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE|wx.RESIZE_BORDER|wx.THICK_FRAME
        wx.Dialog.__init__(self, *args, **kwds)
        self.FunctionViewADiffListCtrl  = FunctionViewDiffListCtrl.FunctionViewDiffListCtrl(self, -1, style=wx.LC_REPORT|wx.SUNKEN_BORDER,top=self.parent,dlg=self,ctrl="A")
        self.FunctionViewBDiffListCtrl  = FunctionViewDiffListCtrl.FunctionViewDiffListCtrl(self, -1, style=wx.LC_REPORT|wx.SUNKEN_BORDER,top=self.parent,dlg=self,ctrl="B")
        self.FunctionViewStatsAListCtrl = FunctionViewStatsListCtrl.FunctionViewStatsListCtrl(self, -1, style=wx.LC_REPORT|wx.SUNKEN_BORDER,top=self.parent,name="A")
        self.FunctionViewStatsBListCtrl = FunctionViewStatsListCtrl.FunctionViewStatsListCtrl(self, -1, style=wx.LC_REPORT|wx.LC_SINGLE_SEL|wx.SUNKEN_BORDER,top=self.parent,name="B")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade
        

        self.FunctionViewADiffListCtrl.Bind(wx.EVT_LIST_ITEM_SELECTED, self.FunctionViewADiffListCtrl.OnItemSelect)
        self.FunctionViewADiffListCtrl.Bind(wx.EVT_LIST_ITEM_RIGHT_CLICK, self.FunctionViewADiffListCtrl.OnRightClick)
        
        self.FunctionViewBDiffListCtrl.Bind(wx.EVT_LIST_ITEM_SELECTED, self.FunctionViewBDiffListCtrl.OnItemSelect)
        self.FunctionViewBDiffListCtrl.Bind(wx.EVT_LIST_ITEM_RIGHT_CLICK, self.FunctionViewBDiffListCtrl.OnRightClick)
        
        
        
        
    def __set_properties(self):
        # begin wxGlade: FunctionViewDifferDlg.__set_properties
        self.SetTitle("dialog_1")
        self.SetSize((796, 418))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: FunctionViewDifferDlg.__do_layout
        sizer_9 = wx.BoxSizer(wx.VERTICAL)
        sizer_11 = wx.BoxSizer(wx.VERTICAL)
        sizer_12 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_10 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_23 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_23.Add(self.FunctionViewADiffListCtrl, 1, wx.EXPAND, 0)
        sizer_23.Add(self.FunctionViewBDiffListCtrl, 1, wx.EXPAND, 0)
        sizer_10.Add(sizer_23, 1, wx.EXPAND, 0)
        sizer_9.Add(sizer_10, 1, wx.ALL|wx.EXPAND, 0)
        sizer_12.Add(self.FunctionViewStatsAListCtrl, 1, wx.ALL|wx.EXPAND, 0)
        sizer_12.Add(self.FunctionViewStatsBListCtrl, 1, wx.ALL|wx.EXPAND, 0)
        sizer_11.Add(sizer_12, 1, wx.ALL|wx.EXPAND, 0)
        sizer_9.Add(sizer_11, 1, wx.ALL|wx.EXPAND, 0)
        self.SetAutoLayout(True)
        self.SetSizer(sizer_9)
        self.Layout()
        # end wxGlade

# end of class FunctionViewDifferDlg


